### ISSUE TITLE
Enable packrat for only 1 or 2 packages

### ISSUE THREAD

**Issue by shapenaji** [rstudio/packrat#370] opened 2017-05-12 16:17 UTC
Running into an issue where I would like to use packrat to control certain problematic packages, but not put every dependency under packrat.

I can sort've do this by setting my external.packages to be every package except the packages in question. 

```
packrat::init(
  options = list(
    external.packages = setdiff(packrat:::appDependencies('.'),'PACKAGE')
  )
)

```
However, if any new package gets added to the code base, I would need to go back and update packrat to set external.packages again.

Is there a way to have a kind of "internal.packages". Such that everything is assumed to be external unless it is included there?

**Comment by shapenaji** [comment] 2017-05-12 16:57
On that note, might be very handy to export the `appDependencies` function. So that we can determine what packages packrat is likely to install

**Comment by kevinushey** [comment] 2017-05-12 17:06
While it's possible to black-list packages with the user of the `ignored.package` option (see `?"packrat::opts"`), it's currently not possible to just provide Packrat with a 'white-list' of packages that it should attempt to track. A number of users have requested this sort of functionality so we should investigate whether it's possible to include in Packrat.

**Comment by colearendt** [comment] 2017-07-13 12:20
Duplicate of #64

**Closed** 2017-07-13 17:41 UTC
