### ISSUE TITLE
Getting "Error in eval(x, envir = envir) : object 'dothis' not found" when using packrat::init()

### ISSUE THREAD

**Issue by philstraforelli** [rstudio/packrat#385] opened 2017-06-29 14:04 UTC
I have a project in which I'm running a `shinydashboard` app to be hosted online. I started out my project by using `packrat` to do the initial set up/one-time wrangling/analysis/etc prior to building the app. Everything worked fine there.

I then wanted to follow [these instructions](https://support.rstudio.com/hc/en-us/articles/216528108-Deploying-packrat-projects-to-Shiny-Server-Pro) to deploy my app on a Shiny server and this is where I'm running into errors. When I specifically run the following command: `packrat::init("~/applications/my-shiny-app") ` (obviously changed the path name accordingly) I get the following feedback:
```
Initializing packrat project in directory:
- "~/Projects/project_name/shinydashboard"
Packrat mode off. Resetting library paths to:
- "C:/Users/PStraforelli/Documents/R/win-library/3.4"
- "C:/Program Files/R/R-3.4.0patched/library"

Adding these packages to packrat:
                   _         
    BH               1.62.0-1
    DT               0.2     
    R.methodsS3      1.7.1   
    R.oo             1.21.0  
    R.utils          2.5.0   
    R6               2.2.2   
    RColorBrewer     1.1-2   
    Rcpp             0.12.11 
    assertthat       0.2.0   
    backports        1.1.0   
    base64enc        0.1-3   
    bindr            0.1     
    bindrcpp         0.2     
    bitops           1.0-6   
    broom            0.4.2   
    caTools          1.17.1  
    cellranger       1.1.0   
    colorspace       1.3-2   
    curl             2.7     
    dichromat        2.0-0   
    digest           0.6.12  
    dplyr            0.7.1   
    evaluate         0.10.1  
    flexdashboard    0.5     
    forcats          0.2.0   
    gdtools          0.1.4   
    ggiraph          0.3.3   
    ggplot2          2.2.1   
    ggrepel          0.6.5   
    glue             1.1.1   
    gtable           0.2.0   
    haven            1.0.0   
    highr            0.6     
    hms              0.3     
    htmltools        0.3.6   
    htmlwidgets      0.8     
    httpuv           1.3.3   
    httr             1.2.1   
    jsonlite         1.5     
    knitr            1.16    
    labeling         0.3     
    lazyeval         0.2.0   
    lubridate        1.6.0   
    magrittr         1.5     
    markdown         0.8     
    matrixStats      0.52.2  
    mime             0.5     
    miniUI           0.1.1   
    mnormt           1.5-5   
    modelr           0.1.0   
    munsell          0.4.3   
    officer          0.1.4   
    openssl          0.9.6   
    packrat          0.4.8-20
    pkgconfig        2.0.1   
    plogr            0.1-1   
    plyr             1.8.4   
    psych            1.7.5   
    purrr            0.2.2.2 
    readr            1.1.1   
    readxl           1.0.0   
    rematch          1.0.1   
    reshape2         1.4.2   
    rlang            0.1.1   
    rmarkdown        1.6     
    rprojroot        1.2     
    rvest            0.3.2   
    rvg              0.1.4   
    scales           0.4.1   
    selectr          0.3-1   
    shiny            1.0.3   
    shinydashboard   0.6.1   
    shinyjs          0.9     
    sourcetools      0.1.6   
    stringi          1.1.5   
    stringr          1.2.0   
    tibble           1.3.3   
    tidyr            0.6.3   
    tidyverse        1.1.1   
    uuid             0.1-2   
    withr            1.0.2   
    xml2             1.1.1   
    xtable           1.8-2   
    yaml             2.1.14  
    zip              1.0.0   

Fetching sources for BH (1.62.0-1) ... OK (CRAN current)
Fetching sources for DT (0.2) ... OK (CRAN current)
Fetching sources for R.methodsS3 (1.7.1) ... OK (CRAN current)
Fetching sources for R.oo (1.21.0) ... OK (CRAN current)
Fetching sources for R.utils (2.5.0) ... OK (CRAN current)
Fetching sources for R6 (2.2.2) ... OK (CRAN current)
Fetching sources for RColorBrewer (1.1-2) ... OK (CRAN current)
Fetching sources for Rcpp (0.12.11) ... OK (CRAN current)
Fetching sources for assertthat (0.2.0) ... OK (CRAN current)
Fetching sources for backports (1.1.0) ... OK (CRAN current)
Fetching sources for base64enc (0.1-3) ... OK (CRAN current)
Fetching sources for bindr (0.1) ... OK (CRAN current)
Fetching sources for bindrcpp (0.2) ... OK (CRAN current)
Fetching sources for bitops (1.0-6) ... OK (CRAN current)
Fetching sources for broom (0.4.2) ... OK (CRAN current)
Fetching sources for caTools (1.17.1) ... OK (CRAN current)
Fetching sources for cellranger (1.1.0) ... OK (CRAN current)
Fetching sources for colorspace (1.3-2) ... OK (CRAN current)
Fetching sources for curl (2.7) ... OK (CRAN current)
Fetching sources for dichromat (2.0-0) ... OK (CRAN current)
Fetching sources for digest (0.6.12) ... OK (CRAN current)
Fetching sources for dplyr (0.7.1) ... OK (CRAN current)
Fetching sources for evaluate (0.10.1) ... OK (CRAN current)
Fetching sources for flexdashboard (0.5) ... OK (CRAN current)
Fetching sources for forcats (0.2.0) ... OK (CRAN current)
Fetching sources for gdtools (0.1.4) ... OK (CRAN current)
Fetching sources for ggiraph (0.3.3) ... OK (CRAN archived)
Fetching sources for ggplot2 (2.2.1) ... OK (CRAN current)
Fetching sources for ggrepel (0.6.5) ... OK (CRAN current)
Fetching sources for glue (1.1.1) ... OK (CRAN current)
Fetching sources for gtable (0.2.0) ... OK (CRAN current)
Fetching sources for haven (1.0.0) ... OK (CRAN current)
Fetching sources for highr (0.6) ... OK (CRAN current)
Fetching sources for hms (0.3) ... OK (CRAN current)
Fetching sources for htmltools (0.3.6) ... OK (CRAN current)
Fetching sources for htmlwidgets (0.8) ... OK (CRAN current)
Fetching sources for httpuv (1.3.3) ... OK (CRAN current)
Fetching sources for httr (1.2.1) ... OK (CRAN current)
Fetching sources for jsonlite (1.5) ... OK (CRAN current)
Fetching sources for knitr (1.16) ... OK (CRAN current)
Fetching sources for labeling (0.3) ... OK (CRAN current)
Fetching sources for lazyeval (0.2.0) ... OK (CRAN current)
Fetching sources for lubridate (1.6.0) ... OK (CRAN current)
Fetching sources for magrittr (1.5) ... OK (CRAN current)
Fetching sources for markdown (0.8) ... OK (CRAN current)
Fetching sources for matrixStats (0.52.2) ... OK (CRAN current)
Fetching sources for mime (0.5) ... OK (CRAN current)
Fetching sources for miniUI (0.1.1) ... OK (CRAN current)
Fetching sources for mnormt (1.5-5) ... OK (CRAN current)
Fetching sources for modelr (0.1.0) ... OK (CRAN current)
Fetching sources for munsell (0.4.3) ... OK (CRAN current)
Fetching sources for officer (0.1.4) ... OK (CRAN current)
Fetching sources for openssl (0.9.6) ... OK (CRAN current)
Fetching sources for packrat (0.4.8-20) ... OK (GitHub)
Fetching sources for pkgconfig (2.0.1) ... OK (CRAN current)
Fetching sources for plogr (0.1-1) ... OK (CRAN current)
Fetching sources for plyr (1.8.4) ... OK (CRAN current)
Fetching sources for psych (1.7.5) ... OK (CRAN current)
Fetching sources for purrr (0.2.2.2) ... OK (CRAN current)
Fetching sources for readr (1.1.1) ... OK (CRAN current)
Fetching sources for readxl (1.0.0) ... OK (CRAN current)
Fetching sources for rematch (1.0.1) ... OK (CRAN current)
Fetching sources for reshape2 (1.4.2) ... OK (CRAN current)
Fetching sources for rlang (0.1.1) ... OK (CRAN current)
Fetching sources for rmarkdown (1.6) ... OK (CRAN current)
Fetching sources for rprojroot (1.2) ... OK (CRAN current)
Fetching sources for rvest (0.3.2) ... OK (CRAN current)
Fetching sources for rvg (0.1.4) ... OK (CRAN current)
Fetching sources for scales (0.4.1) ... OK (CRAN current)
Fetching sources for selectr (0.3-1) ... OK (CRAN current)
Fetching sources for shiny (1.0.3) ... OK (CRAN current)
Fetching sources for shinydashboard (0.6.1) ... OK (CRAN current)
Fetching sources for shinyjs (0.9) ... OK (CRAN current)
Fetching sources for sourcetools (0.1.6) ... OK (CRAN current)
Fetching sources for stringi (1.1.5) ... OK (CRAN current)
Fetching sources for stringr (1.2.0) ... OK (CRAN current)
Fetching sources for tibble (1.3.3) ... OK (CRAN current)
Fetching sources for tidyr (0.6.3) ... OK (CRAN current)
Fetching sources for tidyverse (1.1.1) ... OK (CRAN current)
Fetching sources for uuid (0.1-2) ... OK (CRAN current)
Fetching sources for withr (1.0.2) ... OK (CRAN current)
Fetching sources for xml2 (1.1.1) ... OK (CRAN current)
Fetching sources for xtable (1.8-2) ... OK (CRAN current)
Fetching sources for yaml (2.1.14) ... OK (CRAN current)
Fetching sources for zip (1.0.0) ... OK (CRAN current)
Snapshot written to "C:/Users/PStraforelli/Documents/Projects/project_name/shinydashboard/packrat/packrat.lock"
Installing BH (1.62.0-1) ... 
	OK (downloaded binary)
Installing R.methodsS3 (1.7.1) ... 
	OK (downloaded binary)
Installing R6 (2.2.2) ... 
	OK (downloaded binary)
Installing RColorBrewer (1.1-2) ... 
	OK (downloaded binary)
Installing Rcpp (0.12.11) ... 
	OK (downloaded binary)
Installing assertthat (0.2.0) ... 
	OK (downloaded binary)
Installing backports (1.1.0) ... 
	OK (downloaded binary)
Installing base64enc (0.1-3) ... 
	OK (downloaded binary)
Installing bindr (0.1) ... 
	OK (downloaded binary)
Installing bitops (1.0-6) ... 
	OK (downloaded binary)
Installing colorspace (1.3-2) ... 
	OK (downloaded binary)
Installing curl (2.7) ... 
	OK (downloaded binary)
Installing dichromat (2.0-0) ... 
	OK (downloaded binary)
Installing digest (0.6.12) ... 
	OK (downloaded binary)
Installing glue (1.1.1) ... 
	OK (downloaded binary)
Installing gtable (0.2.0) ... 
	OK (downloaded binary)
Installing highr (0.6) ... 
	OK (downloaded binary)
Installing hms (0.3) ... 
	OK (downloaded binary)
Installing jsonlite (1.5) ... 
	OK (downloaded binary)
Installing labeling (0.3) ... 
	OK (downloaded binary)
Installing lazyeval (0.2.0) ... 
	OK (downloaded binary)
Installing magrittr (1.5) ... 
	OK (downloaded binary)
Installing matrixStats (0.52.2) ... 
	OK (downloaded binary)
Installing mime (0.5) ... 
	OK (downloaded binary)
Installing mnormt (1.5-5) ... 
	OK (downloaded binary)
Installing openssl (0.9.6) ... 
	OK (downloaded binary)
Installing packrat (0.4.8-20) ... 
	OK (built source)
Installing pkgconfig (2.0.1) ... 
	OK (downloaded binary)
Installing plogr (0.1-1) ... 
	OK (downloaded binary)
Installing rematch (1.0.1) ... 
	OK (downloaded binary)
Installing rlang (0.1.1) ... 
	OK (downloaded binary)
Installing sourcetools (0.1.6) ... 
	OK (downloaded binary)
Installing stringi (1.1.5) ... 
	OK (downloaded binary)
Installing uuid (0.1-2) ... 
	OK (downloaded binary)
Installing withr (1.0.2) ... 
	OK (downloaded binary)
Installing xtable (1.8-2) ... 
	OK (downloaded binary)
Installing yaml (2.1.14) ... 
	OK (downloaded binary)
Installing zip (1.0.0) ... 
	OK (downloaded binary)
Installing R.oo (1.21.0) ... 
	OK (downloaded binary)
Installing httpuv (1.3.3) ... 
	OK (downloaded binary)
Installing plyr (1.8.4) ... 
	OK (downloaded binary)
Installing xml2 (1.1.1) ... 
	OK (downloaded binary)
Installing rprojroot (1.2) ... 
	OK (downloaded binary)
Installing caTools (1.17.1) ... 
	OK (downloaded binary)
Installing munsell (0.4.3) ... 
	OK (downloaded binary)
Installing htmltools (0.3.6) ... 
	OK (downloaded binary)
Installing markdown (0.8) ... 
	OK (downloaded binary)
Installing psych (1.7.5) ... 
	OK (downloaded binary)
Installing httr (1.2.1) ... 
	OK (downloaded binary)
Installing bindrcpp (0.2) ... 
	OK (downloaded binary)
Installing tibble (1.3.3) ... 
	OK (downloaded binary)
Installing stringr (1.2.0) ... 
	OK (downloaded binary)
Installing gdtools (0.1.4) ... 
	OK (downloaded binary)
Installing R.utils (2.5.0) ... 
	OK (downloaded binary)
Installing scales (0.4.1) ... 
	OK (downloaded binary)
Installing htmlwidgets (0.8) ... 
	OK (downloaded binary)
Installing shiny (1.0.3) ... 
	OK (downloaded binary)
Installing cellranger (1.1.0) ... 
	OK (downloaded binary)
Installing dplyr (0.7.1) ... 
	OK (downloaded binary)
Installing forcats (0.2.0) ... 
	OK (downloaded binary)
Installing purrr (0.2.2.2) ... 
	OK (downloaded binary)
Installing readr (1.1.1) ... 
	OK (downloaded binary)
Installing evaluate (0.10.1) ... 
	OK (downloaded binary)
Installing lubridate (1.6.0) ... 
	OK (downloaded binary)
Installing reshape2 (1.4.2) ... 
	OK (downloaded binary)
Installing selectr (0.3-1) ... 
	OK (downloaded binary)
Installing DT (0.2) ... 
	OK (downloaded binary)
Installing miniUI (0.1.1) ... 
	OK (downloaded binary)
Installing shinydashboard (0.6.1) ... 
	OK (downloaded binary)
Installing readxl (1.0.0) ... 
	OK (downloaded binary)
Installing tidyr (0.6.3) ... 
	OK (downloaded binary)
Installing haven (1.0.0) ... 
	OK (downloaded binary)
Installing knitr (1.16) ... 
	OK (downloaded binary)
Installing ggplot2 (2.2.1) ... 
	OK (downloaded binary)
Installing rvest (0.3.2) ... 
	OK (downloaded binary)
Installing shinyjs (0.9) ... 
	OK (downloaded binary)
Installing broom (0.4.2) ... 
	OK (downloaded binary)
Installing rmarkdown (1.6) ... 
	OK (downloaded binary)
Installing ggrepel (0.6.5) ... 
	OK (downloaded binary)
Installing officer (0.1.4) ... 
	OK (downloaded binary)
Installing modelr (0.1.0) ... 
	OK (downloaded binary)
Installing flexdashboard (0.5) ... 
	OK (downloaded binary)
Installing rvg (0.1.4) ... 
	OK (downloaded binary)
Installing tidyverse (1.1.1) ... 
	OK (downloaded binary)
Installing ggiraph (0.3.3) ... 
	OK (built source)
Initialization complete!
Error in eval(x, envir = envir) : object 'dothis' not found
Error in eval(x, envir = envir) : object 'dothis' not found
Error in eval(x, envir = envir) : object 'dothis' not found
Error in eval(x, envir = envir) : object 'dothis' not found
Error in eval(x, envir = envir) : object 'dothis' not found
Error in eval(x, envir = envir) : object 'dothis' not found
```

Hmm... Everything is fine, except at the very end. I don't use any object called `dothis` so I have no idea what this is referencing. I decided to ignore this message and tried the following line as per the article above: `packrat::snapshot()` and now things are getting messed up:

```
Error in eval(x, envir = envir) : object 'dothis' not found
In addition: Warning messages:
1: In value[[3L]](cond) :
  Failed to parse C:/Users/PStraforelli/Documents/Projects/project_name/shinydashboard/packrat/lib-R/MASS/scripts/ch16.R ; dependencies in this file will not be discovered.
2: In value[[3L]](cond) :
  Failed to parse C:/Users/PStraforelli/Documents/Projects/project_name/shinydashboard/packrat/lib/x86_64-w64-mingw32/3.4.0/R.oo/misc/ASCII.R ; dependencies in this file will not be discovered.
Error in eval(x, envir = envir) : object 'dothis' not found
Error: Unable to retrieve package records for the following packages:
- "BsMD", "DEoptimR", "DoE.base", "Formula", "FrF2", "GLMMGibbs", "GPArotation", "Hmisc", "Lahman", "LearnBayes", "MatrixModels", "NMF", "RGtk2", "RUnit", "RcppArmadillo", "RcppEigen", "RcppGSL", "SparseM", "SuppDists", "TH.data", "TTR", "XML", "abind", "acepack", "akima", "animation", "arm", "bdsmatrix", "biclust", "bit", "bread", "breakfast", "bubbles", "car", "checkmate", "coda", "combinat", "conf.design", "crayon", "crosstalk", "d3heatmap", "data.table", "deldir", "dendextend", "devtools", "diptest", "doParallel", "dygraphs", "e1071", "estimability", "expm", "fastICA", "flexclust", "flexmix", "foo", "foreach", "forecast", "fpc", "fracdiff", "gWidgetsWWW2", "gam", "gdata", "gee", "gistr", "git2r", "gmodels", "graph", "gridBase", "gridExtra", "gtools", "hexbin", "highcharter", "highlight", "htmlTable", "ibdreg", "igraph", "inline", "irlba", "iterators", "jose", "kernlab", "latticeExtra", "leaflet", "lme4", "lmtest
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  Package 'graph' not available in repository or locally
2: In FUN(X[[i]], ...) :
  Package 'testRcppClass' not available in repository or locally
3: In FUN(X[[i]], ...) :
  Package 'foo' not available in repository or locally
4: In FUN(X[[i]], ...) :
  Package 'testRcppModule' not available in repository or locally
5: In FUN(X[[i]], ...) :
  Package 'shinySignals' not available in repository or locally
6: In FUN(X[[i]], ...) :
  Package 'bubbles' not available in repository or locally
7: In FUN(X[[i]], ...) :
  Package 'gWidgetsWWW2' not available in repository or locally
8: In FUN(X[[i]], ...) :
  Package 'bread' not available in repository or locally
9: In FUN(X[[i]], ...) :
  Package 'oatmeal' not available in repository or locally
```

These seem to be referencing packages that I'm not using, so I'm not sure why they're causing issues. Is there a reason this is happening? Is it because I'm attempting to employ packrat in a project in which I already have packrat employed?

**Comment by kevinushey** [comment] 2017-07-06 17:46
It's really hard to say, but I'm guessing that you do have some usages of something called `dothis` 'somewhere' in that project.

If you do a 'Find in Files' from RStudio (Ctrl + Shift + F) and search for `dothis`, do you see any usages?

**Comment by ClaytonJY** [comment] 2017-10-04 18:49
I'm getting the same error; looks like it's coming from examples in `knitr`, not code I wrote; discovered via `grep`.

My situation is extra tricky in that I just upgraded from 3.4.1 to 3.4.2, triggering full re-bootstrapping of any packrat project I enter for the first time since that upgrade. I've also got two nested RStudio projects, which is a known antipatterns; both use `packrat`, both use `knitr`, only the outer one gives me this issues; the inner one is fine. Lesson learned, don't nest.

None of this is likely to help @philstraforelli, but might give more context to @kevinushey.

The `knitr` used of `dothis` are all in this (and associated .lyx): https://github.com/yihui/knitr/blob/master/inst/examples/knitr-manual.Rnw#L580

Not sure why any of that code would get run, though.

`grep` results below the fold.

<details><pre>
```
▶ grep -R dothis packrat   
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:\texttt{dothis}:
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:dothis=TRUE
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:In the next chunk, we set chunk options \texttt{eval=dothis} and \texttt{echo=!dothis},
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:both are valid R expressions since the variable \texttt{dothis} exists.
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:<<cond-out1, eval=dothis, echo=!dothis>>=
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:print('you cannot see my source because !dothis is FALSE')
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:Then we set \texttt{eval=dothis} and \texttt{echo=dothis} for another
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:<<cond-out2,eval=dothis,echo=dothis>>=
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:If we change the value of \texttt{dothis} to \texttt{FALSE}, neither
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:necessary with the new syntax: \texttt{eval=dothis} will tell R to
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:find the variable \texttt{dothis} automatically just like we call
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.Rnw:a function \texttt{foobar(eval = dothis)}. What is more, all options
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:dothis=TRUE
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:eval=dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:echo=!dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:<<cond-out1, eval=dothis, echo=!dothis>>=
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:print('you cannot see my source because !dothis is FALSE')
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:eval=dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:echo=dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:<<cond-out2,eval=dothis,echo=dothis>>=
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:eval=dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:dothis
packrat/lib/x86_64-pc-linux-gnu/3.4.2/knitr/examples/knitr-manual.lyx:foobar(eval = dothis)
```
</pre></details>

**Comment by kevinushey** [comment] 2017-10-04 21:09
@ClaytonJY: Packrat will crawl your project to discover dependencies (ie, what packages you're actually using in a project); this implies attempting to parse the R code available in e.g. `.Rmd` and `.Rnw` files as well.

Normally, Packrat screens out the `packrat/` directory (that is, the one located at the top-level); however, it doesn't expect to find nested packrat sub-directories, so I suspect that's why you're encountering this issue:

https://github.com/rstudio/packrat/blob/master/R/dependencies.R#L120-L123

I suspect changing that regular expression to be something like:

    packratDirRegex <- paste("(?:^|/)", "packrat", sep = "")

would resolve the issue.

**Comment by ClaytonJY** [comment] 2017-10-04 21:17
@kevinushey thanks for the response; that makes sense. Interesting that of all the sub-project dependencies, that's the only problematic one, but certainly `knitr` does some things no other package would.

This isn't the only issue that I suspect is related to the nesting, but this is all tough to reproduce, and wasn't an issue when I last worked in this project a month ago (before upgrading R), so it's all a big mess. That fix shouldn't hurt anything else, but don't bother just on account of my poor usage pattern.

I wonder why `knitr` examples were getting parsed for OP; they'd have to be in a similar nesting situation, right?

**Comment by kevinushey** [comment] 2017-10-04 21:38
Should be fixed up with https://github.com/rstudio/packrat/commit/cc86af44646ec1dcfbb21878353264cd2f0de6aa -- if you have a chance, you can try installing the development version of Packrat with:

```
devtools::install_github("rstudio/packrat")
```

Let me know if the issue still reproduces or if that takes care of what you're seeing.

**Closed** 2017-10-04 21:37 UTC

**Comment by ClaytonJY** [comment] 2017-10-04 22:26
@kevinushey problem solved! Also seems to have solved some other weirdness I had with packrat picking up dependencies it shouldn't have and throwing weird warnings.

I do have a new issue, though, triggered when a session begins (and packrat inits):
```
Error in symlinkExternalPackages(project = project) : 
  Failed to create 'lib-ext' packrat directory
In addition: Warning message:
In dir.create(libExtDir(project)) :
  cannot create dir '/home/claytonjy/gitlab/groundspeed/doc-field-labeling/packrat/lib-ext/x86_64-pc-linux-gnu/3.4.2', reason 'No such file or directory'
```

looks like packrat now subdirs `lib-ext/` by platform and version, just like it does `lib/`? My existing `lib-ext` just contains a link to the one external package I have setup for this project, `formatR`, so I imagine the error is from trying to do two subdirs at once, `x86_64-pc-linux-gnu/` and `3.4.2/`. Migration issue.

**Comment by kevinushey** [comment] 2017-10-05 03:06
I'll take a look tomorrow and see if I can figure out what's going on.

**Comment by kevinushey** [comment] 2017-10-05 17:00
Should be fixed up now -- let me know if you're still bumping into any issues!

**Comment by ClaytonJY** [comment] 2017-10-05 17:45
Was hard to test, but that fixed it. The error was preventing packrat from initing, which meant I couldn't install packrat inside packrat; so I built the intermediate path, got the old version to init, intstalled the new version, deleted the folder I made, and restarted my R session; bingo.

While I've got you here, there's another weird packrat/knitr interaction; something about the parsing breaks on inline-r code, e.g. `r foo(bar)`. Whenever I restart the session (init packrat) or `packrat::status()`, I get messages like this:
```
Quitting from lines 328-338 (README.Rmd) 
Quitting from lines 48-63 (report.Rmd)
```
which correspond to the first non-code set of lines in the document containing inline code meant to be run when knitting. Usually repeated twice, but over 10 times when I installed the latest packrat.

This wasn't happening previously, though I see https://github.com/yihui/knitr/issues/1441; intalling dev version of knitr failed to fix, not sure where the issue lies.

**Comment by kevinushey** [comment] 2017-10-05 17:53
I suspect this may fix that issue: https://github.com/rstudio/packrat/commit/dc90bf578fdecbb8861bc7eda8f45f5958b636a6

**Comment by ClaytonJY** [comment] 2017-10-05 18:18
@kevinushey unfortunately it does not :(

<details><pre>
> packrat::status()
Quitting from lines 328-338 (README.Rmd) 
Quitting from lines 48-63 (report.Rmd) 
Quitting from lines 74-78 (README.Rmd) 
Quitting from lines 328-338 (README.Rmd) 
Quitting from lines 48-63 (report.Rmd) 
Quitting from lines 74-78 (README.Rmd) 
> devtools::session_info(c("packrat", "knitr"))
Session info -----------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.153)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-10-05                  

Packages ---------------------------------------------------------------------------
 package   * version  date       source                          
 digest      0.6.12   2017-01-27 CRAN (R 3.4.2)                  
 evaluate    0.10.1   2017-06-24 CRAN (R 3.4.2)                  
 graphics  * 3.4.2    2017-09-29 local                           
 grDevices * 3.4.2    2017-09-29 local                           
 highr       0.6      2016-05-09 CRAN (R 3.4.2)                  
 knitr       1.17.4   2017-10-05 Github (yihui/knitr@0dec03b)    
 magrittr    1.5      2014-11-22 CRAN (R 3.4.2)                  
 markdown    0.8      2017-04-20 CRAN (R 3.4.2)                  
 methods   * 3.4.2    2017-09-29 local                           
 mime        0.5      2016-07-07 CRAN (R 3.4.2)                  
 packrat     0.4.8-47 2017-10-05 Github (rstudio/packrat@dc90bf5)
 stats     * 3.4.2    2017-09-29 local                           
 stringi     1.1.5    2017-04-07 CRAN (R 3.4.2)                  
 stringr     1.2.0    2017-02-18 CRAN (R 3.4.2)                  
 tools       3.4.2    2017-09-29 local                           
 utils     * 3.4.2    2017-09-29 local                           
 yaml        2.1.14   2016-11-12 CRAN (R 3.4.2)
<\pre><\details>
