### ISSUE TITLE
Error message when opening packrat project containing Rmd files

### ISSUE THREAD

**Issue by lucygarner** [rstudio/packrat#552] opened 2019-04-23 16:39 UTC
Hi,

When I open my R project that is using packrat, I get an error coming from my Rmarkdown files, specifically from particular parameters in the headers.

`Quitting from lines 379-381 (4-genes_and_TCR_samples.Rmd)` 
`Error in eval(x, envir = envir) : object 'subset_CD3s' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s' not found`

`Quitting from lines 486-488 (4-genes_and_TCR_samples_with_CD3.Rmd)`
`Error in eval(x, envir = envir) : object 'subset_CD3s2' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s2' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s2' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s2' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s2' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s2' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s2' not found`
`Error in eval(x, envir = envir) : object 'subset_CD3s2' not found`

"subset_CD3s: FALSE" is a parameter in the header of "4-genes_and_TCR_samples.Rmd", and "subset_CD3s2: FALSE" is in the header of "4-genes_and_TCR_samples_with_CD3.Rmd".  I have other parameters in the same headers but these don't seem to be causing an error.

What could be the cause of this error and how can I fix it?

Thanks,
Lucy

**Comment by aronatkins** [comment] 2022-02-15 14:02
This problem was caused by using `rmarkdown::render` to analyze R Markdown files for dependencies.

We believe that this is resolved with https://github.com/rstudio/packrat/pull/647.

**Closed by aronatkins** 2022-02-15 14:02 UTC
